:system-name: HuniFood
:system-type: Food dispensing
:author: Gudjon Holm Sigurdsson
:date-started: 29. september 2023
:toc-title: Table of Contents
:toc: top
:version: 0.1
:doc-version: 0.1
:toclevels: 3
:encoding: utf-8
:lang: en
:numbered:
:xrefstyle: short
:chapter-signifier:
:source-highlighter: CodeRay
:source-highlighter: highlight.js
:sectlinks: true
:stylesheet: style.css
:imagesdir: images
:include-dir: ../docs
:stylesdir: {include-dir}/styles
:shell-caption:
:include-dir: ..
ifdef::env-github[]
:include-dir: ../docs
endif::[]
ifdef::env-gitlab[]
:include-dir: ..
endif::[]
ifdef::backend-pdf[]
:pygments-style: zenburn
:source-highlighter: pygments
endif::[]
ifdef::backend-pdf[]
[.shell]
endif::[]
:doctitle: Development v{doc-version} - {system-name} v{version} 

== Introduction

{system-name} is a device designed to help pet owners feed their pets on time with the correct portion size. The device is powered by 230 VAC and is mounted on a wall above the pet's food bowl. It has a container that can hold food for at least a week and dispenses the food into the pet's bowl at a set time. The schedule is configurable, allowing the pet to be fed multiple times a day with different portion sizes. The device can detect when the food storage container is getting empty and will notify the caretaker when it's time to add more food.

To configure the device, the pet owner can use a web browser to command the device and configure it to dispense the correct amount of food at a specified time, as many times a day as needed. The owner can configure multiple schedules, name them, and select which schedules are active at any given time using a web interface.

The device has an easy-to-use interface with buttons and a small display that allows the pet's caretaker to manually dispense food into the pet's bowl and stop the automatic feeding if needed. This is useful if the pet is not on the premises or if the caretaker wants to feed the pet manually with a different food than normal. It's also possible to cancel the next scheduled feeding but continue with the schedule after that. If there is an active feeding schedule, the onboard display will always show the next scheduled feeding time and the amount of food that will be dispensed.

Please note that this document is a living document, and will be updated as the project progresses.

[#.small]#_Ps. Naming of the device comes from the fact my dogs name is Huni and the device is intended to give him food_#.

== Interactions

The Actors(living entities) that interact with the device are the pet, the pet's caretaker and the pet's owner.
Each of them have different roles, responsibilities and knowledge.

.Actors who interact with the device
[cols="^.^10%,.^50%,.^40%", options="header"]
|===
|  *Name*   | *Description*                                           | *Knowledge*         
| Pet       | The animal to be fed, usually a cat or a dog.           | Knows where it's food bowl is.  
| Caretaker | A pet caretaker, pet sitter or just að family member who
              helps taking care of the pet with tasks like feeding it.| Knows how to add food to the device, when the device is running low on food and how to manually feed the pet with one portion of food by pressing a button on the device.
| Owner     | Owner of the pet.  This person determines when 
              the pet should eat, and how big the portions should be. | Knows all a caretaker knows, and additionally knows how to open a browser, and use a web page.
|===





== Project Plan

The {system-name} project is a significant undertaking that I started on {date-started}, and it will likely take over a year to complete. To manage the project, I will break it down into smaller, more manageable sections.

Since I will be working with technologies that I have not used before, I will need to research and create test projects to learn how to wire and use them. Additionally, I will need to design the device's external appearance and internal PCB.

To make the device presentable, I plan to 3D print the necessary parts and design the external appearance of {system-name} by creating a 3D model in Fusion 360 or Sketchup.

=== Project Sections

Quick breakdown, _to be visited later_.

. Figure out the requirements for the device (Introduction)
. Research the different technologies that will be used and create test projects to learn how to use them (Technical Research)
. 3D print the parts needed for the device
. Design the external look of {system-name} by drawing a 3d model of it in Fusion 360 or Sketchup (External Design document)
. Design a PCB to connect the different components to the micro-controller (PCB Design document)
.  Write the software
  * Controller code (Arduino)
  ** Libraries to communicate with the different sensors and motors.
  ** The web service (REST API)
  ** Support for VoffCon
  * Web interface (Web page)

== Technical Research

Getting the food from the container to the pet's bowl is the main task of the device.  
To do that, we need to figure out how to measure the amount of food in the container, and how to dispense the food into the pet's bowl.

To move the food from the storage container to the portion container, we use an auger.
An auger is a screw conveyor that moves the food slowly from the storage container to the portion container.
By doing this slowly, we should be able to measure the amount of food that has been added to the portion container and stop the auger when the correct amount of food has been added.

=== Device Components

==== Micro-controller

_Esp32_ micro-controller will be used to control all the components and receive commands from the owner.

==== Portion Load cell

A _load cell_ will be used to measure the amount of food for each portion.  

==== Food level load cell

A _load cell_ will be used to detect, when the food container is getting empty.  
That is when is the amount of food in the food container is below a the portion amount.

==== Portion motor

A Motor to move the food gradually from the food container to the food portion container.

==== Dispensing motor

When the portion container contains the correct amount of food, we need to dispense it into the pet's bowl.  We will use this motor to do that.

==== Power supply

A 230 VAC to 12 VDC power supply will be used to power the device. To distribute the power to the different components, we will probably use a A _buck converter_ or _step-down converter_.


=== Functional Specification

The Technical research needs to be done to figure out, which components to use and how to use them, before we can write the functional specification.

.Notes

The device will not provide a web interface, but will instead provide a REST API, which can be used by a web page to configure it.

todo: I need to decide if 

 * the device it's self should supply a web interface
 * Should we only support VoffCon
 * Should I write a webpage which is not a VoffCon page, and that webpage uses the devices web service to communicate with it.

todo: (remove) Functional specifications are more concrete and specific. (The how and when of the system). 
todo: (remove) Audience: Developers, testers, and maintainers, who need to know how to build, test, and update the system.


// .An functional descriptive image should be drawn and placed here.
// image::krappur.svg[Interactive,500,opts=inline,align=center]